apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    stand: {{ .Values.stand }}
data:
  redis_password: {{ .Values.env.REDIS_PASSWORD | b64enc }}
type: Opaque
